### ISSUE TITLE
¿Can boolean variables be case insensitive?

### ISSUE THREAD

**Issue by soliddanii** [TriggerReactor/TriggerReactor#11]
I just made an executor for a lightning effect. The first parameter is a boolean (indicates if the lightning does actual damage or is only an effect). If i write true or false all lowercase it works fine, but if I don't the executor does not get the variable and gets a null argument instead. Thank you.

**Comment by wysohn** [comment]
true and false are the 'primitive' types which are not variables.

variables are where you can store data, and primitive type is one of it.

For example, if you have variable named 'TRUE,' you can insert primitive boolean value 'true' into it by
TRUE = true

The reason why Executor is getting null is because using True or tRue or anything other than true/false will be handled as variable not primitive types.

So Trigger Reactor tries to access the variable with that name, but it fails because there's nothing saved in the variable. Consequently, it becomes null as it couldn't find anything.

**Comment by soliddanii** [comment]
I know the difference between a variable and a primitive type. I just didn't choose my technical words correctly. In my opinion the boolean primitive type should be case insensitive and you shouldn't be able to create a variable named True.

**Comment by Sayakie** [comment]
Fixed in #473
