### ISSUE TITLE
Support Java 11

### ISSUE THREAD

**Issue by wysohn** [TriggerReactor/TriggerReactor#286]
In fact, the only thing stopping us from using Java 11 is the fact that Nashorn classes are renamed in Java 9 and above.

We may use reflection to solve the problem.

**Comment by MidnightSugar** [comment]
There are plugins that use nashorn that are now incompatible with java 8. To name a few:

- PlaceholderAPI custom javascript placeholders
- MythicMobsExtension
- PlotSquared world scripts

These are the ones I personally know of, there probably is many more. Switching to Java 11 fixes these problems. I've confirmed this.

However, I cannot upgrade because of TR. This needs to be added sooner rather than later.

**Comment by wysohn** [comment]
@MidnightSugar 
Gotcha, I may push the next updates aside and work on Java 11 support first.

**Comment by wysohn** [comment]
![image](https://user-images.githubusercontent.com/8789836/85178301-fbc01580-b232-11ea-895b-2066d6b49eb2.png)

**Comment by wysohn** [comment]
Sponge API is stuck in Java 8 and will be stuck there for a while, I assume.

Support for Sponge will be paused starting from 3.2.0 until it supports Java 11.

**Comment by wysohn** [comment]
![image](https://user-images.githubusercontent.com/8789836/89461701-2e5d9900-d721-11ea-938a-7eb611b10a42.png)
